Repository animal-squad/project-s-BE, pull requests merged in 2024-11, with the labels that each got.

#15 CI/CD: Dockerfile for prod
  Dockerfile
Labels: 빌드, CI/CD

#16 Fix: modify callback URL
  src/auth/google.strategy.ts
Labels: 버그 수정

#18 Fix: modify callback url
  src/auth/google.strategy.ts
Labels: 버그 수정

#19 PR dev to main
  src/auth/google.strategy.ts
Labels: 버그 수정

#31 Fix: Jenkinsfile 오타 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#32 Fix: Jenkinsfile 오타 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#24 #4 bucket 추가
  package.json
  pnpm-lock.yaml
  prisma/prisma.module.ts
  prisma/prisma.service.ts
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.ts
  src/bucket/bucket.controller.spec.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.module.ts
  src/bucket/bucket.service.spec.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.module.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
  src/user/dto/user.dto.ts
  src/user/user.decorater.ts
  src/utils/time.util.ts
Labels: 기능 추가

#33 Feature/#29
  Jenkinsfile
Labels: 버그 수정, CI/CD

#34 FIx: Jenkinsfile 오타 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#35 Fix: Jenkinsfile 오타 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#36 Fix: Jenkinsfile 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#37 Feature/#29
  Jenkinsfile
Labels: 버그 수정, CI/CD

#39 Fix: Jenkinsfile 내용 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#40 FIx: Jenkinsfile 오타
  Jenkinsfile
Labels: 버그 수정, CI/CD

#41 Fix: Jenkinsfile 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#42 #38 Refactor: bucket 추가 부분 수정
  src/bucket/bucket.controller.ts
  src/bucket/bucket.module.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/link/dto/link.dto.ts
  src/user/user.exception.ts
Labels: 리팩토링, 기능 추가

#45 #43 Feat: 버킷 목록 조회 기능
  package.json
  pnpm-lock.yaml
  src/auth/auth.controller.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.service.ts
  src/utils/pagination.dto.ts
Labels: 기능 추가

#48 #44 Feat: bucket 상세 조회 기능
  prisma/schema.prisma
  src/bucket/bucket.controller.ts
  src/bucket/bucket.service.ts
  src/user/user.decorater.ts
  src/user/user.exception.ts
Labels: 기능 추가

#49 #46 Feat: bucket 공유 기능
  src/bucket/bucket.controller.ts
  src/bucket/bucket.service.ts
Labels: 기능 추가

#50 #47 Feat: bucket 복사하기
  src/bucket/bucket.controller.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.ts
  src/link/link.service.ts
  src/user/user.exception.ts
Labels: 기능 추가

#52 #51 Refactor: 공유 기능 수정
  prisma/schema.prisma
  src/bucket/bucket.controller.ts
  src/bucket/bucket.service.ts
  src/link/dto/link.dto.ts
  src/link/link.service.ts
  src/utils/pagination.dto.ts
Labels: 리팩토링

#55 #54 Feat: bucket 수정 기능
  src/bucket/bucket.controller.ts
  src/bucket/bucket.service.ts
  src/user/user.exception.ts
Labels: 기능 추가

#56 #53 Feat: bucket 삭제 기능
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/bucket/bucket.service.ts
Labels: 기능 추가

#59 #57 Feat: AI 호출 코드 작성
  package.json
  pnpm-lock.yaml
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/bucket/bucket.module.ts
  src/bucket/bucket.service.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.ts
  src/link/link.service.ts
Labels: 기능 추가

#62 #61 Refactor: bucket 복사에서 반환되는 내용 변경
  src/bucket/bucket.service.ts
Labels: 리팩토링

#63 Release: 1차 MVP
  package.json
  pnpm-lock.yaml
  prisma/prisma.module.ts
  prisma/prisma.service.ts
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.ts
  src/bucket/bucket.controller.spec.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/bucket/bucket.module.ts
  src/bucket/bucket.service.spec.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.module.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
  src/user/dto/user.dto.ts
  src/user/user.decorater.ts
  src/user/user.exception.ts
  src/utils/pagination.dto.ts
  src/utils/time.util.ts
Labels: 기능 추가

#65 #64 Refactor: 로그인 수정
  Dockerfile
  Jenkinsfile
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/google.strategy.ts
  src/auth/session.serializer.ts
  src/bucket/bucket.controller.ts
  src/main.ts
  src/session/init.session.ts
  src/session/redis.provider.ts
  src/user/user.controller.ts
  src/user/user.decorater.ts
  src/user/user.service.ts
Labels: 긴급

#69 #68 CI/CD: Jenkinsfile 수정
  Jenkinsfile
Labels: CI/CD

#76 #75 CI/CD: Dockerfile 내용 수정
  Dockerfile
Labels: 기능 추가, CI/CD

#78 #71 Fix: 버그 수정
  src/auth/auth.controller.ts
  src/bucket/bucket.controller.ts
  src/link/link.controller.ts
  src/link/link.service.ts
  src/session/init.session.ts
  src/user/user.controller.ts
  src/user/user.decorator.ts
  src/user/user.exception.ts
Labels: 긴급, 버그 수정

#79 #73 Feat: 링크 제목 수정 기능
  src/link/link.controller.ts
  src/link/link.service.ts
Labels: 기능 추가

#82 #81 Fix: 유저 정보 업데이트
  src/auth/auth.service.ts
  src/auth/google.strategy.ts
  src/auth/session.serializer.ts
  src/user/user.service.ts
Labels: 버그 수정

#84 #74 Feat: 링크의 태그 수정 기능
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
Labels: 기능 추가

#85 #83 Feat: 링크 추가 기능
  src/bucket/bucket.controller.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.module.ts
  src/link/link.service.ts
Labels: 기능 추가

#88 #87 Refactor: 예외처리 추가
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/user/user.exception.ts
Labels: 리팩토링

#89 PR dev to main
  src/auth/auth.service.ts
  src/auth/google.strategy.ts
  src/auth/session.serializer.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.module.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
  src/user/user.exception.ts
  src/user/user.service.ts
Labels: 버그 수정, 기능 추가

#91 #90 Refactor: 이름 저장방식 변경
  src/auth/google.strategy.ts
Labels: 리팩토링

#93 #92 Fix: ai 응답에 대한 에러처리 추가
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
Labels: 버그 수정

#94 PR dev to main
  src/auth/google.strategy.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
Labels: 버그 수정

#95 PR dev to main
  src/bucket/bucket.controller.ts
Labels: 긴급

#97 #86 Feat: 링크 삭제 기능
  prisma/schema.prisma
  src/bucket/bucket.service.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
Labels: 기능 추가

#100 #98 Feat: 링크 조회 기능
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
  src/utils/pagination.dto.ts
Labels: 기능 추가
