Repository animal-squad/project-s-BE, pull requests merged in 2024-12, with the labels that each got.

#101 #99 Docs: swagger 수정
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/extension/extension.controller.spec.ts
  src/extension/extension.controller.ts
  src/extension/extension.module.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.ts
  src/link/link.service.ts
  src/user/dto/user.dto.ts
  src/user/user.controller.ts
  src/user/user.exception.ts
  src/utils/pagination.dto.ts
Labels: 문서 작업

#106 #104 Feat: 키워드 추출 추가로 인한 링크 기능 수정
  license
  prisma/schema.prisma
  src/bucket/dto/bucket.dto.ts
  src/extension/extension.controller.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
  src/utils/pagination.dto.ts
Labels: 기능 추가

#110 #108 Refactor: 관계 테이블 삭제에 따른 코드 수정
  prisma/schema.prisma
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/extension/extension.controller.ts
  src/extension/extension.exeption.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.ts
  src/link/link.exception.ts
  src/link/link.service.spec.ts
  src/link/link.service.ts
Labels: 리팩토링

#112 #111 Feat: 검색 기능 추가
  src/bucket/bucket.controller.spec.ts
  src/bucket/bucket.controller.ts
  src/bucket/bucket.exception.ts
  src/bucket/bucket.module.ts
  src/bucket/bucket.service.ts
  src/bucket/dto/bucket.dto.ts
  src/link/dto/link.dto.ts
  src/link/link.controller.spec.ts
  src/link/link.controller.ts
  src/link/link.service.ts
  src/utils/pagination.dto.ts
Labels: 기능 추가

#114 #113 Feat: sentry 추가
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/link/link.controller.ts
  src/main.ts
  src/sentry.filter.ts
  src/session/init.session.ts
  tsconfig.json
Labels: 기능 추가

#118 Feature/#117
  Dockerfile
Labels: 버그 수정

#119 fix: Dockerfile 수정
  Dockerfile
Labels: 버그 수정

#121 Feature/#117
  Dockerfile
  Jenkinsfile
  pnpm-lock.yaml
Labels: 버그 수정

#122 feat: Test 서버 전용 Jenkinsfile 작성
  Jenkinsfile_test_server
Labels: 기능 추가

#124 #123 Fix: 중복된 응답으로 인한 에러 수정
  src/sentry.filter.ts
Labels: 긴급, 버그 수정

#125 Hotfix: Sentry 필터 수정
  src/sentry.filter.ts
Labels: 긴급, 버그 수정

#131 #130 Fix: 바구니 목록 조회 시 공유 상태가 제대로 전달되지 않는 부분 수정
  src/bucket/bucket.service.ts
Labels: 버그 수정

#129 #128 Fix: 태그 필터 조회 API 수정
  src/link/link.controller.ts
  src/link/link.service.ts
Labels: 버그 수정

#132 Hotfix: 버그 수정
  src/bucket/bucket.service.ts
  src/link/link.controller.ts
  src/link/link.service.ts
Labels: 긴급, 버그 수정

#134 #133 Refactor: 링크와 바구니 처음 저장 시 분류중임을 표시하도록 변경
  src/link/link.service.ts
Labels: 긴급, 리팩토링

#135 PR dev to main
  src/link/link.service.ts
Labels: 긴급

#137 Hotfix: 바구니 복사 로직 수정
  src/bucket/bucket.service.ts
  src/link/link.service.ts
Labels: 긴급
